language: node_js
node_js:
  - '0.10'
  - '0.12'
  - '4'

before_install:
  - npm install -g codeclimate-test-reporter
  - sudo add-apt-repository ppa:qpid/testing -y
  - sudo apt-get update -q
  - sudo apt-get install qpidd qpid-tools
  - sudo sh -c 'echo "auth=no" >> /etc/qpid/qpidd.conf'

before_script:
  - sudo /etc/init.d/qpidd restart
  - sudo qpid-config add exchange topic rpc.request
  - sudo qpid-config add exchange topic rpc.response

script:
  - make coverage

after_script:
  - codeclimate-test-reporter < coverage/lcov.info
